computer_block: NETHER_BRICK_STAIRS
allowed_to_chat: false
camera_head_radius: 0.35
time_to_connect: 3
time_to_disconnect: 3
time_for_spot: 5
camera_inventory_show_item_without_permissions: true
camera-skins:
  "Green Camera": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTM1MTcwNWM3NjVjNGYzNjRjZDk0ZTJjYTk1MjA0ZjdlZWM4YzNjNDdmNDI1ZDZkOTA1MDkwNDVmOTcxNDc2OSJ9fX0="
  "Blue Camera": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzZlNTAyYmM2NzA3ODQ5Zjg1ZTdjMTNmZDYyZTk2ZDZhYmI0ZWM0MTJiMjIxMjNhODdhM2ZiZDQ0ZjcxNDQwZiJ9fX0="
  "White Camera": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjVkODdhNGMzYmJjNDU1NjY1YTU1OTI5NzA4NGUwNTliMjk4NmU1YzIyNThiNDQ5ZWEwZjE3YTBiMTJhZGRhYyJ9fX0="
  "Camera 2": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzRhNzQ0NTdjOTM1OTQ5ZGYxZmU3ZWUzOTViNDhjNDQ4YjMzZTYwMzM0MTMwOTU4NTM2YjE0OGViZDZjNiJ9fX0="
