name: CCTV
version: 8.1
main: io.github.tanguygab.cctv.CCTV
api-version: 1.13
authors: [Streampy, Timdecoole123, Tanguygab]
description: A real CCTV plugin with working CCTV and NPC for a real usage and no invisable players.
softdepend: [ItemsAdder]
commands:
  CCTV:
    description: Main command